name: AlveolEye
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.10
  - pydantic>=2.7.4
  - torchvision>=0.16.2, <=0.17.2
  - napari>=0.4.17
  - pyqt
  - qtpy
  - pytorch
  - pillow>=10.2.0
  - pip
  - gdown
  - numpy<2.0.0
  - pip:
      - opencv-python>=4.1.1.26

