name: AlveolEye
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.10
  - torchvision>=0.16.2
  - napari
  - qtpy
  - pytorch
  - tensorboard
  - pillow
  - pip
  - pip:
      - opencv-python-headless

