name: AlveolEye
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.10
  - torchvision>=0.16.2, <=0.17.2
  - napari
  - pyqt
  - qtpy
  - pytorch
  - pillow
  - pip
  - gdown
  - pip:
      - opencv-python-headless

