name: AlveolEye
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.10
  - pydantic>=1.10.17
  - torchvision>=0.16.2, <=0.17.2
  - napari
  - pyqt
  - qtpy
  - pytorch
  - pillow>=10.2.0
  - pip
  - gdown
  - pip:
      - opencv-python>=4.1.1.26

