name: AlveolEye
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.10
  - torchvision>=0.16.2,<=0.17.2
  - napari
  - pyqt
  - qtpy
  - pytorch
  - tensorboard
  - pillow>=10.2.0
  - gdown
  - pip
  - pip:
      - pycocotools
      - opencv-python>=4.1.1.26
      - pytest
      - pytest-cov
      - pytest-qt

